name: shared/common

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
permissions:
  id-token: write
  contents: read
jobs:
  build-test-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          audience: https://github.com/launchdarkly
          role-to-assume: arn:aws:iam::554582317989:role/github-sdk-js-core
          aws-region: us-east-1
      - uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: '/production/common/releasing/npm/token = NODE_AUTH_TOKEN'
          withDecryption: 'true'
